services:
  catalogdb:
    image: postgres
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432" # Map port 5432 in container to 5432 on the host
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
volumes:
  postgres_catalog:
